# Generated by Django 2.1.5 on 2019-01-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_uploadedfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaFile', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='uploadedFiles',
        ),
    ]
