# Generated by Django 2.1.5 on 2019-01-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20190125_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='mediaFile',
            field=models.FileField(upload_to='media'),
        ),
    ]
