# Generated by Django 2.1.5 on 2019-01-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20190125_0749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileModel',
        ),
    ]
