# Generated by Django 2.1.5 on 2019-01-31 09:13

from django.db import migrations, models
import todoapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='mediaFile',
            field=models.FileField(upload_to='uploadedFiles/', validators=[todoapp.validators.validate_is_zip_or_image, todoapp.validators.size_validator]),
        ),
    ]
